name: Continuous Delivery

on:
  push:
    branches: [ "main", "ci-cd-setup" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Executar testes de CI
        run: |
          echo "Executando testes unitarios e analise de codigo..."
          echo "CI concluido com sucesso!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executar deploy simulado (CD)
        run: |
          echo "Iniciando Continuous Deployment..."
          echo "Deploy realizado com sucesso no ambiente de producao!"
